export const okeiCurveAbi = [
  {
    type: 'function',
    name: 'usdcReserve',
    inputs: [],
    outputs: [{name: '', type: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenReserve',
    inputs: [],
    outputs: [{name: '', type: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'virtualUsdc',
    inputs: [],
    outputs: [{name: '', type: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{name: '', type: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'raiseTarget',
    inputs: [],
    outputs: [{name: '', type: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tradeFeeBps',
    inputs: [],
    outputs: [{name: '', type: 'uint16'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'graduated',
    inputs: [],
    outputs: [{name: '', type: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'Buy',
    inputs: [
      {name: 'buyer', type: 'address', indexed: true},
      {name: 'to', type: 'address', indexed: true},
      {name: 'usdcIn', type: 'uint256', indexed: false},
      {name: 'fee', type: 'uint256', indexed: false},
      {name: 'tokensOut', type: 'uint256', indexed: false},
      {name: 'usdcReserve', type: 'uint256', indexed: false},
      {name: 'tokenReserve', type: 'uint256', indexed: false},
    ],
  },
  {
    type: 'function',
    name: 'buy',
    inputs: [
      {name: 'minTokensOut', type: 'uint256', internalType: 'uint256'},
      {name: 'to', type: 'address', internalType: 'address'},
      {name: 'deadline', type: 'uint256', internalType: 'uint256'},
    ],
    outputs: [{name: 'tokensOut', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'payable',
  },
] as const;
